name: Doxygen-docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - uses: mattnotmitt/doxygen-action@v1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOOM_GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/docs/html
